### ISSUE TITLE
硬件：BOOT模式和调试接口

### ISSUE THREAD

**Issue by taoynkkx** [taoynkkx/LINDIY#7]
1) 不使用BOOT管脚
BOOT0和BOOT1只用BOOT功能。
板子预留BOOT0和3.3V焊盘，用于官方FlashLoader下载使用。
BOOT1电阻下拉到地。

2) 预留下载口
预留串口用于官方FlashLoader下载程序（PA9/10或PA14/15）
方案1：PA9/10接USB串口，PA2/3接LIN。
方案2：PA9/10接LIN保持不变，PA2/3接USB串口不变，PA15引出到PA14附近接下载串口。

3) 不使用调试口
使用其它管脚替换PB3/JTDO和PB4/JNTRST。

**Comment by chaled** [comment]
已经按照上述建议做修改，更新版本到V1.01

**Comment by taoynkkx** [comment]
1的改动，原理图上没问题，需要注意的是布板的时候，留成比较方便的接口，比如2.54插针两个，可以插跳线帽，或者两个不盖油的小孔可以用镊子短接。

**Comment by taoynkkx** [comment]
关于ST-LINK的调试口SWCLK和SWDIO。
只有初期开发和特殊情况下，可能会用到ST-LINK下载程序和调试程序。
中后期主要用FlashLoader通过串口或USB口下载程序，通过串口调试程序。
所以串口会比ST-LINK调试口使用更频繁，电路设计上需要将PA14/PA15/GND放在一个3脚2.54间距的接插件上方便实用，SWCLK和SWDIO只要能够方便飞线出来即可。
SWCLK本身就是PA14，已经接出来，只需要将PA15也引出方便飞线即可。
其他GND/VCC/NRST本身就是很容易飞线出来的，不需要特殊处理。
最终会简化P2这部分电路和空间。

**Comment by taoynkkx** [comment]
原理图我觉得没问题了。
